name: my_currency_exchanger
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.1.1
  firebase_database: ^10.0.1
  firebase_messaging: ^14.0.1
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  http: ^0.13.3

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
